[package]
name = "op-db"
description = "Utilities for managing op-reth's database"
edition = "2021"
resolver = "2"

authors.workspace = true
version.workspace = true

[dependencies]
# External
clap = { version = "4.4.2", features = ["derive"] }
tracing = "0.1.37"
tracing-subscriber = "0.3.17"
anyhow = "1.0.75"

# Local
op-db-utils = { path = "../crates/db-utils" }

[[bin]]
name = "opdb"
path = "src/opdb.rs"
